(synth-fun condition ((count Int) (bufferoffset Int) (LOWFAT_GLOBAL_MS__tif_unix__TIFFmalloc_316 Int)) Bool ((Start Int (3 4 5 -2 -1 0 -3 (+ Start Start) (- Start Start) count bufferoffset LOWFAT_GLOBAL_MS__tif_unix__TIFFmalloc_316)) (StartBool Bool ((< Start Start) (<= Start Start) (and StartBool StartBool) (or StartBool StartBool) (not StartBool)))))
(declare-var count Int)
(declare-var bufferoffset Int)
(declare-var LOWFAT_GLOBAL_MS__tif_unix__TIFFmalloc_316 Int)
(constraint (=> (condition count bufferoffset LOWFAT_GLOBAL_MS__tif_unix__TIFFmalloc_316) (and (<= 4 count) (< (+ -1 (+ bufferoffset (+ -2 count))) LOWFAT_GLOBAL_MS__tif_unix__TIFFmalloc_316))))
(sketch condition (<= 4 count))