#!/bin/bash

PYTHONPATH=/home/gaoxiang/project/crash-free-fix/src/synthesis/eusolver/src:/home/gaoxiang/project/crash-free-fix/src/synthesis/eusolver/../../../infra/z3/build/python:/home/gaoxiang/project/crash-free-fix/src/synthesis/eusolver/thirdparty/libeusolver/build:$PYTHONPATH python3 src/enumerators/enumerators.py

# EOF

